export interface CountryCodeOption {
  code: string;
  name: string;
}

export const countryCodes: CountryCodeOption[] = [
  { code: "+1", name: "Estados Unidos" },
  { code: "+1", name: "Canada" },
  { code: "+52", name: "Mexico" },
  { code: "+54", name: "Argentina" },
  { code: "+55", name: "Brasil" },
  { code: "+56", name: "Chile" },
  { code: "+57", name: "Colombia" },
  { code: "+58", name: "Venezuela" },
  { code: "+591", name: "Bolivia" },
  { code: "+592", name: "Guyana" },
  { code: "+593", name: "Ecuador" },
  { code: "+595", name: "Paraguay" },
  { code: "+598", name: "Uruguay" },
  { code: "+53", name: "Cuba" },
  { code: "+507", name: "Panama" },
  { code: "+506", name: "Costa Rica" },
  { code: "+505", name: "Nicaragua" },
  { code: "+504", name: "Honduras" },
  { code: "+503", name: "El Salvador" },
  { code: "+502", name: "Guatemala" },
  { code: "+501", name: "Belice" },
  { code: "+34", name: "Espana" },
  { code: "+351", name: "Portugal" },
  { code: "+33", name: "Francia" },
  { code: "+49", name: "Alemania" },
  { code: "+39", name: "Italia" },
  { code: "+41", name: "Suiza" },
  { code: "+31", name: "Paises Bajos" },
  { code: "+32", name: "Belgica" },
  { code: "+44", name: "Reino Unido" },
  { code: "+43", name: "Austria" },
  { code: "+420", name: "Republica Checa" },
  { code: "+421", name: "Eslovaquia" },
  { code: "+36", name: "Hungria" },
  { code: "+40", name: "Rumania" },
  { code: "+48", name: "Polonia" },
  { code: "+47", name: "Noruega" },
  { code: "+46", name: "Suecia" },
  { code: "+45", name: "Dinamarca" },
  { code: "+358", name: "Finlandia" },
  { code: "+372", name: "Estonia" },
  { code: "+371", name: "Letonia" },
  { code: "+370", name: "Lituania" },
  { code: "+386", name: "Eslovenia" },
  { code: "+385", name: "Croacia" },
  { code: "+387", name: "Bosnia y Herzegovina" },
  { code: "+382", name: "Montenegro" },
  { code: "+381", name: "Serbia" },
  { code: "+389", name: "Macedonia del Norte" },
  { code: "+30", name: "Grecia" },
  { code: "+357", name: "Chipre" },
  { code: "+356", name: "Malta" },
  { code: "+353", name: "Irlanda" },
  { code: "+380", name: "Ucrania" },
  { code: "+7", name: "Rusia" },
  { code: "+1", name: "Puerto Rico" },
  { code: "+1", name: "Jamaica" },
  { code: "+1", name: "Republica Dominicana" },
  { code: "+1", name: "Trinidad y Tobago" },
  { code: "+1", name: "Barbados" },
  { code: "+1", name: "Bahamas" },
  { code: "+1", name: "Santa Lucia" },
  { code: "+1", name: "Granada" },
  { code: "+1", name: "San Vicente y las Granadinas" },
  { code: "+1", name: "Antigua y Barbuda" },
  { code: "+1", name: "San Cristobal y Nieves" },
];
