export interface CountryCodeOption {
  code: string;
  name: string;
}

const rawCountryCodes: CountryCodeOption[] = [
  { code: "+1", name: "Estados Unidos" },
  { code: "+1", name: "Canada" },
  { code: "+52", name: "Mexico" },
  { code: "+54", name: "Argentina" },
  { code: "+55", name: "Brasil" },
  { code: "+56", name: "Chile" },
  { code: "+57", name: "Colombia" },
  { code: "+58", name: "Venezuela" },
  { code: "+591", name: "Bolivia" },
  { code: "+592", name: "Guyana" },
  { code: "+593", name: "Ecuador" },
  { code: "+595", name: "Paraguay" },
  { code: "+598", name: "Uruguay" },
  { code: "+53", name: "Cuba" },
  { code: "+507", name: "Panama" },
  { code: "+506", name: "Costa Rica" },
  { code: "+505", name: "Nicaragua" },
  { code: "+504", name: "Honduras" },
  { code: "+503", name: "El Salvador" },
  { code: "+502", name: "Guatemala" },
  { code: "+501", name: "Belice" },
  { code: "+34", name: "Espana" },
  { code: "+351", name: "Portugal" },
  { code: "+33", name: "Francia" },
  { code: "+49", name: "Alemania" },
  { code: "+39", name: "Italia" },
  { code: "+41", name: "Suiza" },
  { code: "+31", name: "Paises Bajos" },
  { code: "+32", name: "Belgica" },
  { code: "+44", name: "Reino Unido" },
  { code: "+43", name: "Austria" },
  { code: "+420", name: "Republica Checa" },
  { code: "+421", name: "Eslovaquia" },
  { code: "+36", name: "Hungria" },
  { code: "+40", name: "Rumania" },
  { code: "+48", name: "Polonia" },
  { code: "+47", name: "Noruega" },
  { code: "+46", name: "Suecia" },
  { code: "+45", name: "Dinamarca" },
  { code: "+358", name: "Finlandia" },
  { code: "+372", name: "Estonia" },
  { code: "+371", name: "Letonia" },
  { code: "+370", name: "Lituania" },
  { code: "+386", name: "Eslovenia" },
  { code: "+385", name: "Croacia" },
  { code: "+387", name: "Bosnia y Herzegovina" },
  { code: "+382", name: "Montenegro" },
  { code: "+381", name: "Serbia" },
  { code: "+389", name: "Macedonia del Norte" },
  { code: "+30", name: "Grecia" },
  { code: "+357", name: "Chipre" },
  { code: "+356", name: "Malta" },
  { code: "+353", name: "Irlanda" },
  { code: "+380", name: "Ucrania" },
  { code: "+7", name: "Rusia" },
  { code: "+1", name: "Puerto Rico" },
  { code: "+1", name: "Jamaica" },
  { code: "+1", name: "Republica Dominicana" },
  { code: "+1", name: "Trinidad y Tobago" },
  { code: "+1", name: "Barbados" },
  { code: "+1", name: "Bahamas" },
  { code: "+1", name: "Santa Lucia" },
  { code: "+1", name: "Granada" },
  { code: "+1", name: "San Vicente y las Granadinas" },
  { code: "+1", name: "Antigua y Barbuda" },
  { code: "+1", name: "San Cristobal y Nieves" },
  { code: "+1", name: "Samoa Americana" },
  { code: "+1", name: "Guam" },
  { code: "+1", name: "Islas Marianas del Norte" },
  { code: "+61", name: "Australia" },
  { code: "+64", name: "Nueva Zelanda" },
  { code: "+674", name: "Nauru" },
  { code: "+675", name: "Papua Nueva Guinea" },
  { code: "+676", name: "Tonga" },
  { code: "+677", name: "Islas Salomon" },
  { code: "+678", name: "Vanuatu" },
  { code: "+679", name: "Fiyi" },
  { code: "+680", name: "Palaos" },
  { code: "+681", name: "Wallis y Futuna" },
  { code: "+682", name: "Islas Cook" },
  { code: "+683", name: "Niue" },
  { code: "+685", name: "Samoa" },
  { code: "+686", name: "Kiribati" },
  { code: "+687", name: "Nueva Caledonia" },
  { code: "+688", name: "Tuvalu" },
  { code: "+689", name: "Polinesia Francesa" },
  { code: "+690", name: "Tokelau" },
  { code: "+691", name: "Micronesia" },
  { code: "+692", name: "Islas Marshall" },
  { code: "+60", name: "Malasia" },
  { code: "+62", name: "Indonesia" },
  { code: "+63", name: "Filipinas" },
  { code: "+65", name: "Singapur" },
  { code: "+66", name: "Tailandia" },
  { code: "+670", name: "Timor-Leste" },
  { code: "+673", name: "Brunei" },
  { code: "+7", name: "Kazajistan" },
  { code: "+81", name: "Japon" },
  { code: "+82", name: "Corea del Sur" },
  { code: "+84", name: "Vietnam" },
  { code: "+850", name: "Corea del Norte" },
  { code: "+852", name: "Hong Kong" },
  { code: "+853", name: "Macao" },
  { code: "+855", name: "Camboya" },
  { code: "+856", name: "Laos" },
  { code: "+86", name: "China" },
  { code: "+880", name: "Banglades" },
  { code: "+886", name: "Taiwan" },
  { code: "+90", name: "Turquia" },
  { code: "+91", name: "India" },
  { code: "+92", name: "Pakistan" },
  { code: "+93", name: "Afganistan" },
  { code: "+94", name: "Sri Lanka" },
  { code: "+95", name: "Myanmar" },
  { code: "+960", name: "Maldivas" },
  { code: "+961", name: "Libano" },
  { code: "+962", name: "Jordania" },
  { code: "+963", name: "Siria" },
  { code: "+964", name: "Iraq" },
  { code: "+965", name: "Kuwait" },
  { code: "+966", name: "Arabia Saudita" },
  { code: "+967", name: "Yemen" },
  { code: "+968", name: "Oman" },
  { code: "+970", name: "Palestina" },
  { code: "+971", name: "Emiratos Arabes Unidos" },
  { code: "+972", name: "Israel" },
  { code: "+973", name: "Barein" },
  { code: "+974", name: "Catar" },
  { code: "+975", name: "Bhutan" },
  { code: "+976", name: "Mongolia" },
  { code: "+977", name: "Nepal" },
  { code: "+98", name: "Iran" },
  { code: "+992", name: "Tayikistan" },
  { code: "+993", name: "Turkmenistan" },
  { code: "+994", name: "Azerbaiyan" },
  { code: "+995", name: "Georgia" },
  { code: "+996", name: "Kirguistan" },
  { code: "+998", name: "Uzbekistan" },
  { code: "+374", name: "Armenia" },
];

export const countryCodes: CountryCodeOption[] = [...rawCountryCodes].sort((a, b) =>
  a.name.localeCompare(b.name, "es", { sensitivity: "base" }),
);
